from enum import Enum

class ErrorTypes(Enum):
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    EXTENSION_NOT_FOUND = "EXTENSION_NOT_FOUND"
    EXTENSION_RELOAD_ERROR = "EXTENSION_RELOAD_ERROR"
    EXTENSION_UNLOAD_ERROR = "EXTENSION_UNLOAD_ERROR"
    EXTENSION_LOAD_ERROR = "EXTENSION_LOAD_ERROR"
    INVALID_INPUT = "INVALID_INPUT"
    INVALID_FILE_TYPE = "INVALID_FILE_TYPE"
    UNKNOWN = "UNKNOWN"