"""This module defines all default costants.. normaly used as fallback values."""

from .cache_constants import CACHE_DIR, CACHE_INDEX_FILE
from .cli_constants import DEFAULT_DEBUG_FLAG
from .config_loaders_constants import DEFAULT_ENV_CONFIG_PATH, DEFAULT_LOADERS_PATH, DEFAULT_YAML_CONFIG_PATH, YAML_FILE_ENCODING, DEFAULT_MAPPERS_PATH
from .conventional_constants import UNKNOWN_FILE_SIZE, DEFAULT_STRING_DIVISOR, DEFAULT_DOWNLOAD_BLACKLIST_SITES
from .discord_constants import DEFAULT_COMMANDS_PATH, DEFAULT_DISCORD_RECONNECT
from .drive_constants import DRIVE_BASE_FILE_UPLOAD_URL, DRIVE_MAX_RETRY_COUNT
from .temp_constants import DEFAULT_TEMP_DIR
from .ytdlp_constants import DEFAULT_DOWNLOAD_FORMAT, DEFAULT_YT_DLP_SETTINGS, DEFAULT_DOWNLOAD_FILESIZE_LIMIT
from .redis_constants import DEFAULT_REDIS_HOST, DEFAULT_REDIS_PORT, DEFAULT_REDIS_USERNAME, DEFAULT_REDIS_PASSWORD, DEFAULT_REDIS_CACHE_DB, DEFAULT_REDIS_LOGIN_DB

__all__ = [
    "CACHE_DIR",
    "CACHE_INDEX_FILE",
    "DEFAULT_DEBUG_FLAG",
    "DEFAULT_ENV_CONFIG_PATH",
    "DEFAULT_LOADERS_PATH",
    "DEFAULT_YAML_CONFIG_PATH",
    "YAML_FILE_ENCODING",
    "UNKNOWN_FILE_SIZE",
    "DEFAULT_STRING_DIVISOR",
    "DEFAULT_COMMANDS_PATH",
    "DEFAULT_DISCORD_RECONNECT",
    "DRIVE_BASE_FILE_UPLOAD_URL",
    "DRIVE_MAX_RETRY_COUNT",
    "DEFAULT_TEMP_DIR",
    "DEFAULT_DOWNLOAD_FORMAT",
    "DEFAULT_YT_DLP_SETTINGS",
    "DEFAULT_DOWNLOAD_BLACKLIST_SITES"
    "DEFAULT_DOWNLOAD_FILESIZE_LIMIT",
    "DEFAULT_REDIS_HOST",
    "DEFAULT_REDIS_PORT",
    "DEFAULT_REDIS_USERNAME",
    "DEFAULT_REDIS_PASSWORD",
    "DEFAULT_REDIS_CACHE_DB",
    "DEFAULT_REDIS_LOGIN_DB",
    "DEFAULT_MAPPERS_PATH",
]