
DEFAULT_REDIS_HOST: str = "localhost"
DEFAULT_REDIS_PORT: int = 6379
DEFAULT_REDIS_CACHE_DB: int = 0
DEFAULT_REDIS_LOGIN_DB: int = 1
DEFAULT_REDIS_USERNAME: str | None = None
DEFAULT_REDIS_PASSWORD: str | None = None