from enum import Enum

class ErrorTypes(Enum):
    """Defines error types"""
    UNKNOWN = "UNKNOWN"
    BOT_DISCORD_ERROR = "BOT_DISCORD_ERROR"
    DISCORD_ERROR = "DISCORD_ERROR"
    DOWNLOAD_ERROR = "DOWNLOAD_ERROR"
    DOWNLOAD_FAILED = "DOWNLOAD_FAILED"
    LOADER_ERROR = "LOADER_ERROR"
    STORAGE_ERROR = "STORAGE_ERROR"
    UPLOAD_FAILED = "UPLOAD_FAILED"
    BLACKLISTED_SEARCH = "BLACKLISTED_SEARCH"
    INVALID_URL = "INVALID_URL"